---
title: "kable tables"
author: "LEw"
format: html
editor: visual
---

```{r}
library(tidyverse)
library(lterdatasampler)
library(kableExtra)

# remotes::install_github("lter/lterdatasampler")
```

Create a summary table of mean maple seedling height (cm\^2) and sd of maple seedling height grouped by watershed and year

```{r}
hbr_summary <- hbr_maples %>%
  group_by(watershed, year) %>%
  summarise(mean_height = round(mean(stem_length, na.rm = TRUE), 1),
            sd_height = round(sd(stem_length, na.rm = TRUE), 2))
```

make a nicer table with it!

```{r}
hbr_summary |> 
  kable() |> 
  kable_styling(bootstrap_options = "striped")

hbr_summary |> 
  kable() |> 
  kable_classic(bootstrap_options = "striped")

hbr_summary |> 
  kable(col.names = c("Watershed", "Year", "Mean Seedling Height (sq. cm)", "SD Seedling height (sq. cm)")) |> 
  kable_styling(bootstrap_options = "striped") |> 
  column_spec(1, bold = TRUE, background = "skyblue") |> 
  add_header_above(c(" " = 2, "Seedling Dimensions" = 2)) |> 
  scroll_box(height = "200px", width = "200px")
```
